class ArcanumHandler : EventHandler
{
	override void PlayerEntered(PlayerEvent e)
	{
		ArcanumSpellBrain brain = ArcanumSpellBrain.Get(e.PlayerNumber);
		brain.InitSpells(false); // [Ace] Because PostBeginPlay seems to be called a bit too late on it. In fact, it doesn't seem to be called at all.
	}

	override void NetworkProcess(ConsoleEvent e)
	{
		if (e.Name ~== "ARC_ReInitSpells")
		{
			ArcanumSpellBrain brain = ArcanumSpellBrain.Get(e.Player);
			brain.InitSpells(e.Args[0]);
		}
	}
}